<?php
if(isset($_COOKIE['lang']) && $_COOKIE['lang'] == "fr"){
$lang = $_COOKIE['lang'];
$title = "Gestion des élèves - Système de gestion scolaire";
$ok_button = "D'accord";
$cancel_button = "Annuler";
$leave = "Sortie";
$save = "Enregistrer";
$addstudent = "Ajouter un élève";
$name = "Prenom";
$fn = "Nom";
$gender = "Sexe";
$gender0 = "Mâle";
$gender1 = "Femelle";
$dob = "Date de naissance";
$email = "Adresse e-mail";
$pn = "Numéro de téléphone";
$pw = "Mot de passe";
$class = "Classe";
$div = "Division";
$year = "Niveau scolaire";
$school = "École";
$choose = "--Sélectionner--";
$allfields = "Tous les champs sont requis";
$exportcsv = "Exporter CSV";
$exportexcel = "Exporter EXCEL";
$importexcel = "Importer EXCEL";
$exportpdf = "Exporter PDF";
$print = "Imprimer";
$copy = "Copier";
$val = "Statut du compte";
$val0 = "Activé";
$val1 = "Désactivé";
$chars8 = "Il doit s'agir de 8 lettres / symboles / nombres ou plus";
$leavepass = "Laissez-le vide si vous ne voulez pas modifier le mot de passe";
$printcard = "Imprimer la carte scolaire";
$schoolcard = "Carte scolaire";
$and = "et";
$passwordshort = "Mot de passe trop court";
$excelli1 = "Dans la colonne 'Sexe': 0 = Mâle, 1 = Femelle.";
$excelli2 = "Dans la colonne 'École': le code de l'école.";
$excelli3 = "Dans la colonne 'Niveau scolaire': le code du niveau scolaire.";
$excelli4 = "Dans la colonne 'Division': le code du division.";
$excelli5 = "Dans la colonne 'Classe': le code du classe.";
$excelli6 = "Dans la colonne 'Statut du compte': 0 = Activé, 1 = Désactivé.";
}else{
$lang = "ar";
$title = "تسيير التلاميذ - نظام إدارة المدارس";
$ok_button = "موافق";
$cancel_button = "إلغاء";
$leave = "خروج";
$save = "حفظ";
$addstudent = "إضافة تلميذ";
$name = "الإسم";
$fn = "اللقب";
$gender = "الجنس";
$gender0 = "ذكر";
$gender1 = "أنثى";
$dob = "تاريخ الميلاد";
$email = "البريد الإلكتروني";
$pn = "رقم الهاتف";
$pw = "كلمة المرور";
$class = "القسم";
$div = "الشعبة";
$year = "المستوى التعليمي";
$school = "المدرسة";
$choose = "--إختر--";
$allfields = "جميع الحقول مطلوبة";
$exportcsv = "تصدير CSV";
$exportexcel = "تصدير EXCEL";
$importexcel = "إستيراد EXCEL";
$exportpdf = "تصدير PDF";
$print = "طباعة";
$copy = "نسخ";
$val = "حالة الحساب";
$val0 = "مفعل";
$val1 = "غير مفعل";
$chars8 = "يجب أن تكون 8 حروف / رموز / أرقام أو أكثر";
$leavepass = "اتركها فارغة إذا كنت لا تريد تغيير كلمة المرور";
$printcard = "طباعة البطاقة المدرسية";
$schoolcard = "البطاقة المدرسية";
$and = "و";
$passwordshort = "كلمة المرور قصيرة جدا";
$excelli1 = "في العمود 'الجنس': 0 = ذكر، 1 = أنثى.";
$excelli2 = "في العمود 'المدرسة': رمز المدرسة.";
$excelli3 = "في العمود 'المستوى التعليمي': رمز المستوى التعليمي.";
$excelli4 = "في العمود 'الشعبة': رمز الشعبة.";
$excelli5 = "في العمود 'القسم': رمز القسم.";
$excelli6 = "في العمود 'حالة الحساب': 0 = مفعل، 1 = غير مفعل.";
}
?>