<?php
if(isset($_COOKIE['lang']) && $_COOKIE['lang'] == "fr"){
$lang = $_COOKIE['lang'];
$title = "Gestion des utilisateurs - Système de gestion scolaire";
$ok_button = "D'accord";
$cancel_button = "Annuler";
$leave = "Sortie";
$save = "Enregistrer";
$adduser = "Ajouter un utilisateur";
$permissions = "Permissions";
$name = "Prenom";
$fn = "Nom";
$gender = "Sexe";
$gender0 = "Mâle";
$gender1 = "Femelle";
$dob = "Date de naissance";
$email = "Adresse e-mail";
$pn = "Numéro de téléphone";
$pw = "Mot de passe";
$school = "École";
$choose = "--Sélectionner--";
$allfields = "Tous les champs sont requis";
$exportcsv = "Exporter CSV";
$exportexcel = "Exporter EXCEL";
$importexcel = "Importer EXCEL";
$exportpdf = "Exporter PDF";
$print = "Imprimer";
$copy = "Copier";
$val = "Statut du compte";
$val0 = "Activé";
$val1 = "Désactivé";
$chars8 = "Il doit s'agir de 8 lettres / symboles / nombres ou plus";
$leavepass = "Laissez-le vide si vous ne voulez pas modifier le mot de passe";
$passwordshort = "Mot de passe trop court";
$excelli1 = "Dans la colonne 'Sexe': 0 = Mâle, 1 = Femelle.";
$excelli2 = "Dans la colonne 'École': le code de l'école.";
$excelli3 = "Dans la colonne 'Type': superadmins = Superadmin, admins = Admin.";
$excelli4 = "Dans la colonne 'Statut du compte': 0 = Activé, 1 = Désactivé.";
$type = "Type";
$type0 = "Superadmin";
$type1 = "Admin";
}else{
$lang = "ar";
$title = "تسيير المستخدمين - نظام إدارة المدارس";
$ok_button = "موافق";
$cancel_button = "إلغاء";
$leave = "خروج";
$save = "حفظ";
$adduser = "إضافة مستخدم";
$permissions = "الصلاحيات";
$name = "الإسم";
$fn = "اللقب";
$gender = "الجنس";
$gender0 = "ذكر";
$gender1 = "أنثى";
$dob = "تاريخ الميلاد";
$email = "البريد الإلكتروني";
$pn = "رقم الهاتف";
$pw = "كلمة المرور";
$school = "المدرسة";
$choose = "--إختر--";
$allfields = "جميع الحقول مطلوبة";
$exportcsv = "تصدير CSV";
$exportexcel = "تصدير EXCEL";
$importexcel = "إستيراد EXCEL";
$exportpdf = "تصدير PDF";
$print = "طباعة";
$copy = "نسخ";
$val = "حالة الحساب";
$val0 = "مفعل";
$val1 = "غير مفعل";
$chars8 = "يجب أن يكون 8 حروف / رموز / أرقام أو أكثر";
$leavepass = "اتركها فارغة إذا كنت لا تريد تغيير كلمة المرور";
$passwordshort = "كلمة المرور قصيرة جدا";
$excelli1 = "في العمود 'الجنس': 0 = ذكر، 1 = أنثى.";
$excelli2 = "في العمود 'المدرسة': رمز المدرسة.";
$excelli3 = "في العمود 'النوع': superadmins = مشرف رئيسي، admins = مشرف.";
$excelli4 = "في العمود 'حالة الحساب': 0 = مفعل، 1 = غير مفعل.";
$type = "النوع";
$type0 = "مشرف رئيسي";
$type1 = "مشرف";
}
?>